### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by DHuangs** [tera-private-mods/Auto-Guildquest#1]
hello , I'm using this mod in menma's TERA and the following error occurred. How can I solve it?

![12345](https://github.com/tera-private-mods/Auto-Guildquest/assets/31302913/e5ea41cf-4526-4125-b2bd-7507f0c45165)

**Comment by justkeepquiet** [comment]
Hi. For stable operation of all modules we recommended to use this version of the TeraToolbox: https://github.com/tera-private-toolbox/tera-toolbox
